# This docker-compose is only for local
services:
  sonarqube-db:
    image: postgres:17-alpine
    container_name: sonarqube-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonardb
    volumes:
      - ./_local/data/sonarqube_db/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      start_period: 1m
      start_interval: 5s
      interval: 1m
      timeout: 10s
      retries: 3

  sonarqube:
    image: ${DOCKER_REGISTRY:-adrianmusante}/sonarqube:0.0.0
    container_name: sonarqube
    restart: unless-stopped
    build:
      context: sonarqube
    depends_on:
      sonarqube-db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - BITNAMI_DEBUG=${BITNAMI_DEBUG:-true}
      - SONARQUBE_DATABASE_HOST=sonarqube-db
      - SONARQUBE_DATABASE_PORT_NUMBER=5432
      - SONARQUBE_DATABASE_NAME=sonardb
      - SONARQUBE_DATABASE_USER=sonar
      - SONARQUBE_DATABASE_PASSWORD=sonar
      - SONARQUBE_USERNAME=${SONARQUBE_USERNAME:-admin}
      - SONARQUBE_PASSWORD=${SONARQUBE_PASSWORD:-admin123}
      - SONARQUBE_CE_JAVA_ADD_OPTS=${SONARQUBE_CE_JAVA_ADD_OPTS:--Xmx1192m}
      - SONARQUBE_WEB_JAVA_ADD_OPTS=${SONARQUBE_WEB_JAVA_ADD_OPTS:--Xmx1192m}
      - SONARQUBE_ELASTICSEARCH_JAVA_ADD_OPTS=${SONARQUBE_ELASTICSEARCH_JAVA_ADD_OPTS:-}
      - SONARQUBE_EXTRA_PROPERTIES=${SONARQUBE_EXTRA_PROPERTIES:-}
      - SONARQUBE_EXTRA_SETTINGS=${SONARQUBE_EXTRA_SETTINGS:-}
      - SONARQUBE_WEB_URL=${SONARQUBE_WEB_URL:-}
      - SONARQUBE_EMAIL_FROM_ADDRESS=${SONARQUBE_EMAIL_FROM_ADDRESS:-}
      - SONARQUBE_EMAIL_FROM_NAME=${SONARQUBE_EMAIL_FROM_NAME:-}
    volumes:
      - ./_local/data/sonarqube:/bitnami/sonarqube
    ports:
      - "9000:9000"
    healthcheck:
      test: health-check
      start_period: 3m
      start_interval: 10s
      interval: 1m
      timeout: 10s
      retries: 3

networks:
  default:
    name: sonarqube_network
    driver: bridge
