# This docker-compose is only for local
services:
  sonarqube_db:
    image: postgres:16-alpine
    container_name: sonarqube_db
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonardb
    ports:
      - "5432:5432"
    volumes:
      - ./_local/data/sonarqube_db/data:/var/lib/postgresql/data

  sonarqube:
    image: ${DOCKER_REGISTRY:-adrianmusante}/sonarqube:0.0.0
    container_name: sonarqube
    build:
      context: sonarqube
    depends_on:
      - sonarqube_db
    env_file:
      - .env
    environment:
      - BITNAMI_DEBUG=${BITNAMI_DEBUG:-true}
      - SONARQUBE_DATABASE_HOST=sonarqube_db
      - SONARQUBE_DATABASE_PORT_NUMBER=5432
      - SONARQUBE_DATABASE_NAME=sonardb
      - SONARQUBE_DATABASE_USER=sonar
      - SONARQUBE_DATABASE_PASSWORD=sonar
      - SONARQUBE_USERNAME=${SONARQUBE_USERNAME:-admin}
      - SONARQUBE_PASSWORD=${SONARQUBE_PASSWORD:-admin123}
      - SONARQUBE_CE_JAVA_ADD_OPTS=${SONARQUBE_CE_JAVA_ADD_OPTS:--Xmx1192m}
      - SONARQUBE_WEB_JAVA_ADD_OPTS=${SONARQUBE_WEB_JAVA_ADD_OPTS:--Xmx1192m}
      - SONARQUBE_ELASTICSEARCH_JAVA_ADD_OPTS=${SONARQUBE_ELASTICSEARCH_JAVA_ADD_OPTS:-}
      - SONARQUBE_EXTRA_PROPERTIES=${SONARQUBE_EXTRA_PROPERTIES:-}
      - SONARQUBE_EXTRA_SETTINGS=${SONARQUBE_EXTRA_SETTINGS:-}
      - SONARQUBE_WEB_URL=${SONARQUBE_WEB_URL:-}
      - SONARQUBE_EMAIL_FROM_ADDRESS=${SONARQUBE_EMAIL_FROM_ADDRESS:-}
      - SONARQUBE_EMAIL_FROM_NAME=${SONARQUBE_EMAIL_FROM_NAME:-}
    ports:
      - "9000:9000"
    volumes:
      - ./_local/data/sonarqube:/bitnami/sonarqube

networks:
  default:
    name: sonarqube_network
    driver: bridge
