name: Close stale issues and PRs

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-message: 'This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs.'
          stale-pr-message: 'This pull request has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs.'
          stale-issue-label: 'stale'
          stale-pr-label: 'stale'
          operations-per-run: 500
          days-before-stale: 30
          days-before-close: 7
          delete-branch: false
          include-only-assigned: true
          exempt-issue-labels: 'awaiting-approval,work-in-progress,on-hold'
          exempt-pr-labels: 'awaiting-approval,work-in-progress,on-hold'
