name: Update Version

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

env:
  DEPENDENCY_NAME: SonarQube
  DOCKERFILE_PATH: sonarqube/Dockerfile
  DOCKERFILE_VERSION_KEY: SONARQUBE_VERSION
  DOCKERFILE_PR_PLUGIN_VERSION_KEY: SONARQUBE_PR_PLUGIN_VERSION

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure Git user
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: Get latest version
        id: get-latest
        run: |
          version="$(curl -sSfL -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' https://api.github.com/repos/mc1arke/sonarqube-community-branch-plugin/releases/latest | json_pp | grep '"tag_name"' | cut -d '"' -f4 | tr -d '\\n' | tr -d 'v')"
          if [ -z "$version" ]; then
            echo "Failed to fetch latest version" >&2
            exit 1
          fi
          # Ensure that the SonarQube Docker image and the plugin use the same version number
          docker_tag_status=$(curl -s -o /dev/null -w "%{http_code}" "https://hub.docker.com/v2/repositories/bitnami/sonarqube/tags/$version/")
          if [ "$docker_tag_status" -ne 200 ]; then
            echo "::warning::Docker tag $version does not exist in bitnami/sonarqube"
            exit 1
          fi
          echo "Latest version: $version"          
          echo "version=$version" >> $GITHUB_OUTPUT
      - name: Get current version
        id: get-current
        run: |
          version="$(grep -Po "ARG $DOCKERFILE_VERSION_KEY=\K[0-9.]*" "$DOCKERFILE_PATH")"
          echo "Current version: $version"
          echo "version=$version" >> $GITHUB_OUTPUT
      - name: Check if update is needed
        id: check
        run: |
          if [ "${{ steps.get-latest.outputs.version }}" = "${{ steps.get-current.outputs.version }}" ]; then
            echo "up_to_date=true" >> $GITHUB_OUTPUT
          else
            echo "up_to_date=false" >> $GITHUB_OUTPUT
          fi
      - name: Pull request metadata
        if: steps.check.outputs.up_to_date == 'false'
        id: pr
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          version="${{ steps.get-latest.outputs.version }}"
          title="Update $DEPENDENCY_NAME to v$version"
          prs=$(gh pr list --search "$title" --json title | jq length)
          if [ "$prs" -gt 0 ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi
          echo "title=$title" >> $GITHUB_OUTPUT
          echo "body=Bumps $DEPENDENCY_NAME to version $version" >> $GITHUB_OUTPUT
          echo "head_branch=update/v$version" >> $GITHUB_OUTPUT
          echo "base_branch=main" >> $GITHUB_OUTPUT
      - name: Create Pull Request
        if: steps.pr.outputs.exists == 'false' && steps.check.outputs.up_to_date == 'false'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          version="${{ steps.get-latest.outputs.version }}"
          branch="${{ steps.pr.outputs.head_branch }}"
          git checkout -b "$branch"
          sed -i "s|ARG $DOCKERFILE_VERSION_KEY=.*|ARG $DOCKERFILE_VERSION_KEY=$version|" "$DOCKERFILE_PATH"
          sed -i "s|ARG $DOCKERFILE_PR_PLUGIN_VERSION_KEY=.*|ARG $DOCKERFILE_PR_PLUGIN_VERSION_KEY=$version|" "$DOCKERFILE_PATH"
          sed -i -E "s|-\s*\[\`[0-9]+\`,\s*\`[0-9.]+\`,\s*\`latest\` \(${DOCKERFILE_PATH}\)\]|- [\`$(echo "$version" | cut -d'.' -f1,1)\`, \`$(echo "$version" | cut -d'.' -f1,2)\`, \`latest\` (${DOCKERFILE_PATH})]|" README.md
          git commit -am "Update version to $version"
          git push origin "$branch"
          gh pr create --title "${{ steps.pr.outputs.title }}" \
            --body "${{ steps.pr.outputs.body }}" \
            --base "${{ steps.pr.outputs.base_branch }}" --head "$branch"